### ISSUE TITLE
Support for Debian buster

### ISSUE THREAD

**Issue by fmmarques** [s-h-3-l-l/katoolin3#38]
Hi! Nice work!

I've been trying to use the script to install the tools and I keep getting the following error:

"Reading package lists...
Error with package armitage: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Trying to ignore this...
Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 714, in install
    self._cache[pkg].mark_install()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1556, in mark_install
    fixer.resolve(True)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 1166, in <module>
    main()
  File "/usr/local/bin/katoolin3", line 1099, in main
    choice()
  File "/usr/local/bin/katoolin3", line 1034, in view_categories
    view_packages(choice)
  File "/usr/local/bin/katoolin3", line 1003, in view_packages
    method(choices)
  File "/usr/local/bin/katoolin3", line 723, in install
    self._cache[pkg].mark_delete()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1531, in mark_delete
    fix.resolve()
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
"

Do you have any idea of if his can be fixed?

**Comment by OBBrain** [comment]
Same for me, hoping for a fix.

Edit: I still see that '......this may be caused by held packages", but i managed to let the installer get all the tools he could find. 
My solution:

sudo apt-get clean
sudo apt-get -f install
sudo apt-get autoremove
