### ISSUE TITLE
Error when running Install Everything

### ISSUE THREAD

**Issue by Tiebe** [s-h-3-l-l/katoolin3#45]
**Describe the bug**
When I run Katoolin3 and select install everything, I get the following errors:

```
Hit:1 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease
Hit:2 http://nl.archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease
Hit:5 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease
Get:4 http://kali.download/kali kali-rolling InRelease [30,5 kB]
Get:6 http://kali.download/kali kali-rolling/main amd64 Packages [16,5 MB]
Hit:7 http://packages.elementary.io/appcenter bionic InRelease
Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]
Hit:9 http://nl.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:10 http://nl.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:11 http://kali.download/kali kali-rolling/contrib amd64 Packages [101 kB]
Get:12 http://kali.download/kali kali-rolling/non-free amd64 Packages [199 kB]
Fetched 16,9 MB in 1min 16s (222 kB/s)
Reading package lists...


DISCLAIMER:
Don't update your packages, upgrade your system or
modify your package cache in any other way while 
katoolin3 is still running!


Main Menu
0) View Categories              
1) Install All                  
2) Uninstall All                
3) Search repository            
4) List installed packages      
5) List not installed packages  
6) Install Kali Menu            
7) Uninstall old katoolin       
8) Help                         
9) Exit                         

kat> 1

Install everything?
0) Yes  
1) No   

kat> 0
Reading package lists...
Warning: Could not find package 'cuckoo'
Error with package guymager: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Trying to ignore this...
Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 714, in install
    self._cache[pkg].mark_install()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1534, in mark_install
    fixer.resolve(True)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 1166, in <module>
    main()
  File "/usr/local/bin/katoolin3", line 1099, in main
    choice()
  File "/usr/local/bin/katoolin3", line 926, in install_all_packages
    APT.install(all_packages())
  File "/usr/local/bin/katoolin3", line 723, in install
    self._cache[pkg].mark_delete()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1509, in mark_delete
    fix.resolve()
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**To Reproduce**
Install Everything

**Expected behavior**
Install Everything

**Desktop:**
 - OS: ElementaryOS

**Comment by redfishstix** [comment]
Same error here! I can't seem to pinpoint where the problem is. Thanks!
